---
label: Service
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: short_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Short Description
- name: icon
  type: text
  config:
    required: false
  label: Icon
pages:
- _services/bespoke-web-design.md
- _services/custom-web-development.md
- _services/custom-wordpress-development.md
- _services/wordpress-optimisation.md
